### ISSUE TITLE
install 부분 오타 발견했습니다

### ISSUE THREAD

**Issue by yjj8353** [work6kr/work6-php-framework#1]
![id](https://user-images.githubusercontent.com/38521736/60064849-b4e13200-973c-11e9-9b6b-31a8e2ce5ad1.png)

중간에 아아디로 오타나 있네요.

**Comment by work6kr** [comment]
감사합니다.
님의 의견으로 다음과 같이 수정되었습니다.
https://github.com/work6kr/work6-php-framework/commit/9c59364e350225a8ca321bb7cca073be7d139944
